# Generated by Django 3.2.18 on 2023-04-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_complete_postings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='best_postings',
            new_name='best_today',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='complete_postings',
            new_name='complete_today',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='like_postings',
            new_name='like_today',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sad_postings',
            new_name='sad_today',
        ),
    ]
